version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: event_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Flask Backend
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/event_management
      SECRET_KEY: your-super-secret-key-here
      JWT_SECRET_KEY: your-jwt-secret-key-here
      FLASK_ENV: production
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  # React Frontend
  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: